version: "3.2"
services:
  mongodb:
    image: mongo:3.6.0-jessie
    ports:
      - 27017:27017
    healthcheck:
      disable: true
    networks:
      - workenv
  mysql:
    image: mariadb:10.1.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 101internet
      MYSQL_PASSWORD: 101internet
    networks:
      - workenv
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5010:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - workenv
  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379
    networks:
      - workenv
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - workenv
networks:
  workenv:
    external: true
